services:
  postgres:
    image: postgres:16-alpine
    container_name: dkfitt-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dkfitt
      POSTGRES_PASSWORD: dkfitt
      POSTGRES_DB: dkfitt
    volumes:
      - dkfitt_pg_data:/var/lib/postgresql/data

volumes:
  dkfitt_pg_data:
